import { IconAlertTriangle, IconArrowDown, IconArrowFork, IconArrowRight, IconBoxMultiple, IconCaretDown, IconCaretUp, IconCheck, IconCircle, IconCircleCaretDown, IconCircleCaretUp, IconCircleCheck, IconCircleDot, IconCircleOff, IconCirclePlus, IconCircleX, IconDeviceFloppy, IconDownload, IconFile, IconFolderOpen, IconHelp, IconInfoCircle, IconMinus, IconPackageExport, IconPencil, IconPhotoCancel, IconPhotoCheck, IconPhotoDown, IconPlayerSkipBack, IconPlayerSkipForward, IconPlayerTrackNext, IconPlus, IconRefresh, IconSettings, IconSquareNumber1, IconStack, IconTrash, IconX, TablerIconsProps } from '@tabler/icons-react';

export type IconProps = TablerIconsProps;
export type IconFunc = (props: IconProps) => React.ReactNode;

export const Icons = {
  Help: IconHelp,
  Delete: IconTrash,
  Warning: IconAlertTriangle,
  ArrowDown: IconArrowDown,
  ArrowFork: IconArrowFork,
  ArrowRight: IconArrowRight,
  ImportProject: IconDownload,
  BlankProject: IconFile,
  NewFile: IconFile,
  OpenFile: IconFolderOpen,
  SaveFile: IconDeviceFloppy,
  Exportfile: IconPackageExport,
  CaretUp: IconCaretUp,
  CaretDown: IconCaretDown,
  Options: IconSettings,
  Plus: IconPlus,
  CirclePlus: IconCirclePlus,
  Minus: IconMinus,
  Close: IconX,
  Block: IconCircleOff,
  X: IconX,
  Circle: IconCircle,
  CircleDot: IconCircleDot,
  CircleX: IconCircleX,
  Check: IconCheck,
  CircleCheck: IconCircleCheck,
  CircleCaretUp: IconCircleCaretUp,
  CircleCaretDown: IconCircleCaretDown,
  Prev: IconPlayerSkipBack,
  Next: IconPlayerSkipForward,
  NextAll: IconPlayerTrackNext,
  PhotoLossless: IconPhotoCheck,
  PhotoLossy: IconPhotoDown,
  PhotoError: IconPhotoCancel,
  Edit: IconPencil,
  CompositeSubframes: IconStack,
  SingleLayered: IconSquareNumber1,
  MultiLayered: IconBoxMultiple,
  Info: IconInfoCircle,
  Reset: IconRefresh,
} as const satisfies Record<string, IconFunc>;
